name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    # Runs tests in parallel with matrix strategy
    strategy:
      fail-fast: false
      matrix:
        containers: [1,2,3,4,5] # Uses 2 parallel instances

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        # Uses the official Cypress GitHub action
        uses: cypress-io/github-action@v6
        with:
          # Starts web server for E2E tests - replace with your own server invocation
          start: npm start
          wait-on: 'http://localhost:3000' # Waits for above

          # Records to Cypress Cloud 
          record: true

          # Enable parallelization
          parallel: true

          # ðŸ‘‡ NEW: label each machine (optional but useful)
          group: github-actions-${{ matrix.containers }}

          # ðŸ‘‡ NEW: SAME build id for all matrix jobs
          ci-build-id: ${{ github.run_id }}

        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # GitHub token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
